-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Servidor: 127.0.0.1:3306
-- Tiempo de generación: 17-11-2022 a las 04:40:50
-- Versión del servidor: 5.7.36
-- Versión de PHP: 7.4.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `lit`
--
CREATE DATABASE IF NOT EXISTS `lit` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `lit`;

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `company`
--

DROP TABLE IF EXISTS `company`;
CREATE TABLE IF NOT EXISTS `company` (
  `ID` int(5) NOT NULL AUTO_INCREMENT COMMENT 'unique ID of company',
  `name` text NOT NULL COMMENT 'company''s name',
  `tagline` text NOT NULL COMMENT 'company''s tagline',
  `description` text NOT NULL COMMENT 'company''s description',
  `logo` text NOT NULL COMMENT 'company''s filename',
  `image` text NOT NULL COMMENT 'company''scomplementary image filename',
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COMMENT='company''s information';

--
-- Volcado de datos para la tabla `company`
--

INSERT INTO `company` (`ID`, `name`, `tagline`, `description`, `logo`, `image`) VALUES
(1, 'Bounteous', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Mauris viverra molestie augue non maximus. Praesent sit amet libero eget turpis imperdiet aliquam quis vel lacus. Donec nec consequat nunc. Morbi ultricies sapien in accumsan faucibus. Integer porttitor id nulla ac posuere. Donec eget hendrerit mauris. Donec placerat diam magna, a tristique metus bibendum a. Curabitur maximus efficitur nibh, et blandit ex bibendum id.', 'company.png', 'companyEnv.png'),
(2, 'American Tower Corporation', 'Nullam ut orci in risus tempor consequat sed suscipit ipsum.', 'Fusce imperdiet accumsan enim sed mollis. In vulputate dolor ac venenatis sagittis. Proin vestibulum, orci ac luctus fermentum, lacus lacus dictum lorem, et condimentum tortor eros ac magna. Aliquam erat volutpat. Praesent mollis dictum nunc ut volutpat. In sit amet neque lectus. Phasellus nisl tortor, pharetra in justo a, mollis varius mi. Curabitur dictum ex vitae justo pharetra placerat. Donec in efficitur nunc. Sed in eleifend nisl. Integer et arcu quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus gravida ut risus eu sagittis.', 'company.png', 'companyEnv.png'),
(3, 'Netflix', 'Curabitur a sapien consequat, vestibulum purus quis, lobortis arcu.', 'Cras egestas venenatis arcu, at fringilla elit congue quis. Quisque ultricies sapien non lorem scelerisque dapibus. In tincidunt bibendum lacus, a tristique orci tristique id. Phasellus id hendrerit nisi. Ut pulvinar, diam at dignissim pulvinar, dolor nisi viverra purus, sit amet dapibus neque orci vel justo. Mauris in augue metus. Sed arcu ex, lacinia at pharetra et, iaculis nec elit. Sed luctus mi sit amet nibh suscipit, ac consectetur ex feugiat.', 'company.png', 'companyEnv.png'),
(4, 'Charles Schwab', 'Cras eget metus in felis laoreet placerat.', 'Curabitur vitae scelerisque quam, nec fermentum purus. Mauris efficitur accumsan massa in pellentesque. Aliquam pulvinar turpis in suscipit ultricies. Maecenas nec arcu quis quam sagittis rhoncus. Pellentesque maximus tincidunt porta. Proin accumsan auctor leo laoreet consequat. Cras imperdiet nulla a quam convallis aliquam. Sed scelerisque nibh ac fermentum dapibus.', 'company.png', 'companyEnv.png'),
(5, 'Latinas in Tech', 'Curabitur varius arcu vitae ornare finibus.', 'Nullam sit amet viverra magna, non aliquam sem. Duis sed sodales nisi, nec pretium augue. Sed ligula quam, pharetra eget tempor non, vestibulum quis lectus. Nulla cursus tincidunt enim eget tristique. Aenean vel lobortis elit. Mauris ac dapibus libero. Sed vitae libero in ex dapibus cursus nec et elit. Ut malesuada congue ante, a consectetur eros rutrum eu.', 'company.png', 'companyEnv.png'),
(6, 'Qualtrics', 'Nulla eu turpis viverra, pellentesque odio vitae, pellentesque ligula.', 'Fusce vitae gravida ipsum. Mauris volutpat ipsum non imperdiet vestibulum. Fusce non quam ex. Vivamus et elit vulputate, aliquam mauris eget, dictum nulla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean tempor, odio at tempor maximus, eros enim ullamcorper tellus, ut commodo erat metus a justo. Nullam id orci eget urna ullamcorper consequat. Nullam pellentesque nisi vel ante feugiat dignissim. Aliquam nec eros lorem. Integer sed viverra ipsum.', 'company.png', 'companyEnv.png'),
(7, 'Wikimedia Foundation', 'Donec id erat ut arcu ultrices semper a in mi.', 'Sed non suscipit augue, in blandit lorem. Morbi consectetur in arcu ac cursus. Sed commodo tellus non auctor venenatis. Donec neque mauris, vestibulum eget ipsum eu, ultrices interdum nunc. Quisque tellus quam, iaculis vitae facilisis dignissim, sollicitudin sed nisl. Integer dui est, varius sed lorem vitae, hendrerit posuere dolor. Suspendisse potenti. Aenean nec velit et mi cursus iaculis.', 'company.png', 'companyEnv.png'),
(8, 'Honeycomb.io', 'Cras eu urna ullamcorper, tincidunt nisl at, accumsan velit.', 'Nulla ipsum turpis, dignissim in iaculis ut, auctor et elit. Aenean ullamcorper mattis mauris, non ultrices lorem gravida ac. Phasellus placerat tristique justo, vel pretium sem tincidunt vitae. Integer posuere ligula ut nulla tincidunt ultricies. Morbi vel mattis sem. Duis vel dapibus ligula. Duis feugiat elit sapien, in bibendum sapien accumsan id. Sed venenatis lobortis sem et condimentum.', 'company.png', 'companyEnv.png'),
(9, 'Nike', 'Phasellus ac erat egestas, iaculis augue eu, sollicitudin sem.', 'Ut aliquam ullamcorper mi sed pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget facilisis libero, non porttitor ex. Proin nibh libero, tincidunt venenatis metus at, eleifend auctor erat. Nam velit nisi, hendrerit vitae erat vitae, mollis vehicula erat. Fusce auctor nisl at justo sagittis, sit amet suscipit purus vestibulum. In congue tempor justo, sed convallis purus posuere a. Proin posuere nunc tincidunt augue pulvinar viverra vel eget enim. Suspendisse porta fermentum nibh nec dignissim.', 'company.png', 'companyEnv.png'),
(10, 'Federal Reserve Bank of San Francisco', 'Nullam condimentum eros eget ante vestibulum, ut consectetur dui cursus.', 'Aliquam erat volutpat. Donec hendrerit quam at lectus faucibus, quis porta erat congue. In vitae aliquam leo. Integer scelerisque euismod magna a blandit. Vivamus mattis, ante eget eleifend maximus, justo purus aliquet erat, vel ullamcorper arcu nunc ac arcu. Maecenas porttitor lobortis mauris in fringilla. Morbi tempus eros non odio laoreet, sit amet ullamcorper felis aliquet.', 'company.png', 'companyEnv.png'),
(11, 'State Compensation Insurance Fund', 'Etiam vehicula libero ut eleifend lacinia.', 'Pellentesque sed quam cursus, posuere nunc a, imperdiet ante. Nam id interdum sem. Pellentesque tempus, quam et varius tincidunt, ipsum orci ornare eros, eget ornare sapien diam eu odio. Cras viverra, sem quis varius fermentum, metus felis lobortis erat, molestie luctus eros justo eget odio. Integer pharetra varius purus, vitae dignissim urna iaculis nec. Proin quis sodales dolor. Proin eleifend, diam et iaculis suscipit, elit neque dignissim magna, vitae mollis ex sem vel felis. Maecenas fringilla tempor imperdiet. Integer convallis dui ut nibh tempor interdum. Ut ornare eleifend rutrum. Suspendisse aliquet tempor dictum. Curabitur eget posuere sapien. Quisque eleifend est ullamcorper fermentum rutrum. Aliquam convallis mi nec lacus congue blandit. Duis ac leo sit amet dolor molestie viverra eu ac lectus.', 'company.png', 'companyEnv.png'),
(12, 'Black Knight', 'Mauris nec urna bibendum justo hendrerit aliquam non ut nisl.', 'Integer nunc purus, blandit sit amet sodales sit amet, porttitor ornare felis. Proin eleifend accumsan libero eu ultrices. Phasellus fringilla malesuada quam in hendrerit. Sed dignissim lacus quis elementum congue. Vestibulum ut faucibus lorem. Vestibulum vel nisl sed nulla luctus interdum. Nullam vitae mollis urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris felis est, pellentesque vitae lacus sit amet, blandit sollicitudin ipsum. Curabitur commodo, dolor et accumsan feugiat, nisl ex vestibulum odio, in molestie libero metus ac nisi. Nulla facilisi.', 'company.png', 'companyEnv.png'),
(13, 'Lattice', 'Nulla ornare elit vel volutpat tempus.', 'Aenean quis purus in tellus fermentum aliquet ac eu ipsum. Integer rutrum commodo ipsum, eget porta leo mattis ac. Nunc ornare est mi, vel lobortis lorem feugiat sed. Praesent ornare massa quis ornare vestibulum. Quisque urna mauris, fermentum eu rutrum sed, ornare vel dolor. Pellentesque odio nulla, iaculis bibendum quam porta, lobortis tempus felis. Mauris eleifend ante aliquet consequat venenatis. Sed sodales, ipsum ut pharetra vestibulum, augue libero scelerisque neque, vestibulum ultrices urna est ac est. Quisque et augue molestie, mollis metus sit amet, varius sem. Aliquam malesuada est at ullamcorper dictum. Nam scelerisque sapien ut felis malesuada fringilla. Curabitur vel iaculis leo.', 'company.png', 'companyEnv.png'),
(14, 'Firemon', 'Pellentesque vitae dolor egestas, lobortis elit sit amet, vulputate urna.', 'Aenean ultricies lacus nec rhoncus lacinia. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam velit elit, semper at velit at, gravida rhoncus augue. Etiam est dui, blandit malesuada sem vitae, interdum vulputate dui. Nulla dictum nisl id erat dictum mattis. Curabitur eu luctus justo. Integer convallis elit at diam sollicitudin pellentesque. Praesent vel augue ac diam consequat malesuada eget auctor tortor. Duis laoreet auctor tempor. Morbi posuere velit sed arcu tempor varius. Nullam in lacinia dui.', 'company.png', 'companyEnv.png'),
(15, 'Amazon', 'Donec eget felis eget enim gravida rutrum venenatis sed eros.', 'Phasellus rutrum varius justo. Donec enim mauris, gravida et enim a, fringilla interdum enim. Quisque ligula sem, tristique eget sagittis a, consectetur eu nisi. Duis dapibus ultrices leo at aliquam. Etiam elit nisl, egestas id justo quis, ornare tempor ligula. Mauris sed sapien nisi. Suspendisse dui nisi, cursus in finibus convallis, aliquam nec tellus. Duis dignissim condimentum lectus ac scelerisque. Cras viverra odio vel dictum tincidunt. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur mollis nisi a lorem tempus, a luctus dolor cursus. Etiam pellentesque non urna non dapibus. Nam id efficitur risus. Vivamus eu augue massa.', 'company.png', 'companyEnv.png'),
(16, 'InfoTrust', 'Donec non elit quis arcu iaculis luctus.', 'In ut felis metus. Suspendisse ac risus lacinia, faucibus turpis non, varius ex. Curabitur ut finibus diam, in facilisis mi. Vestibulum non diam viverra, aliquet justo vitae, molestie odio. Maecenas hendrerit libero eleifend tincidunt lobortis. Nullam egestas risus sed lacus vulputate, ac fermentum lectus fermentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras vel mi non leo malesuada porta. Duis ipsum ipsum, tincidunt eu ipsum et, consectetur ornare felis. Phasellus porta metus ut ligula consectetur, vel eleifend erat aliquam.', 'company.png', 'companyEnv.png'),
(17, 'Asana', 'Sed sit amet est et nulla dignissim commodo.', 'Maecenas orci enim, posuere ut hendrerit vel, feugiat eget arcu. Maecenas vitae quam turpis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam a augue fringilla, vestibulum ligula quis, feugiat arcu. Nulla eget ex posuere, sagittis diam ornare, aliquam ex. Suspendisse potenti. Ut commodo mauris nisi, rhoncus ultricies metus tincidunt sit amet. Aenean feugiat urna ut ex sodales, a auctor dolor vehicula. Sed dictum nec sapien eu rhoncus. Nulla mollis aliquam erat. Sed in lorem condimentum, tincidunt metus quis, mattis leo. Nunc non placerat est.', 'company.png', 'companyEnv.png'),
(18, 'Chronosphere', 'Mauris quis mi euismod, placerat tellus eleifend, rhoncus arcu.', 'Ut vel neque vitae odio fringilla congue. Cras semper elit eu aliquet consectetur. Donec tempor elit ut ligula vulputate, at congue velit eleifend. Sed in neque ultrices est finibus sodales. Morbi dapibus, elit sed lobortis finibus, nunc nunc rhoncus nisl, ac aliquam mauris eros non massa. Nam nisi est, pulvinar in egestas quis, ornare sit amet mauris. In nisi ante, dictum scelerisque lorem id, ultricies mollis lorem. Nam at pulvinar metus. Integer vel vulputate leo. Aliquam erat volutpat. Quisque turpis est, feugiat sit amet interdum et, viverra eget sapien. Vestibulum malesuada elementum dui at scelerisque. Duis feugiat neque eu quam tincidunt varius vehicula et odio. Sed faucibus in sem vitae gravida.', 'company.png', 'companyEnv.png'),
(19, 'Orum.io', 'Suspendisse tempor turpis non condimentum suscipit.', 'Ut sit amet congue arcu. Nullam cursus feugiat nibh, a varius purus rhoncus at. Maecenas quam mi, suscipit vel lorem sit amet, commodo tempus urna. Nam at magna lectus. Sed augue orci, tincidunt in erat id, iaculis fermentum justo. Sed non metus laoreet, semper odio id, maximus metus. Nullam vestibulum metus iaculis ipsum pulvinar tempus non fringilla justo. Duis quis consectetur tortor. Pellentesque eget turpis et nisi ultricies eleifend id sed lacus. Nullam vehicula ultricies felis eget viverra. Etiam laoreet viverra nunc, quis hendrerit nisl mattis sit amet. Aenean pulvinar sodales dolor, consequat suscipit mi porttitor nec.', 'company.png', 'companyEnv.png'),
(20, 'VMWare', 'Donec vel risus vitae augue laoreet vehicula.', 'Phasellus tincidunt magna ac pellentesque scelerisque. Ut pretium finibus purus a aliquam. Nulla at vestibulum ipsum, vitae suscipit diam. Vestibulum vitae bibendum nunc, id porta dolor. Maecenas nunc ipsum, rhoncus ut laoreet sed, pellentesque eu eros. Aenean pulvinar erat quam, a ullamcorper felis venenatis sit amet. Cras laoreet, leo id sodales mollis, ipsum justo suscipit ante, ut efficitur velit dui quis turpis. Proin vitae varius dolor, nec porta diam.', 'company.png', 'companyEnv.png'),
(21, 'Omidyar Network', 'In eget ex vel elit venenatis tincidunt.', 'Sed ullamcorper ullamcorper augue sed imperdiet. Suspendisse non neque rhoncus, rhoncus mi sed, accumsan nisl. Nulla dignissim porta ante at congue. Nullam posuere neque in ante tempus vestibulum. Mauris a leo ac mauris luctus egestas. Donec eu nibh a lectus laoreet pharetra. Etiam auctor dignissim arcu quis volutpat. Sed congue odio non leo suscipit, ut ultricies diam fermentum. Etiam non porta leo. Etiam posuere, massa ornare porta bibendum, sapien tellus posuere purus, non pharetra tellus dui interdum leo. In hac habitasse platea dictumst. Donec sit amet rutrum orci, nec congue mauris. Sed quis tempus sapien. Phasellus sed sapien vitae nisi scelerisque interdum non vel nisi. Fusce orci ante, euismod ut risus ut, dignissim tincidunt lectus.', 'company.png', 'companyEnv.png'),
(22, 'GFiber', 'Donec porta lacus eget congue pellentesque.', 'Morbi ultricies enim non aliquet aliquet. Etiam efficitur lacinia sapien malesuada vehicula. Fusce nibh massa, feugiat id tortor quis, vehicula bibendum nulla. Curabitur molestie mollis porttitor. Ut euismod ante sapien, a blandit augue interdum in. In sagittis dui magna, ut commodo lorem gravida auctor. Maecenas elementum justo est, interdum ultrices odio pretium non. Vivamus faucibus leo neque, sit amet tincidunt felis fermentum sed. Sed ultrices nisi ut lacinia mattis. Cras vitae tempus quam. Quisque velit dolor, ornare ut lobortis bibendum, efficitur in lacus. Mauris at interdum nulla. Maecenas eget ex orci. Aenean pulvinar sem vel sapien mollis, vitae tempus purus ultricies. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae;', 'company.png', 'companyEnv.png'),
(23, 'SoFi', 'Sed et erat ut turpis imperdiet commodo.', 'Sed elementum massa vitae lectus sollicitudin, at sodales justo congue. Praesent ac pretium metus. In a orci sit amet diam tempus laoreet. Cras maximus ante in eleifend dictum. Vivamus urna ligula, scelerisque nec nulla eu, porttitor semper lacus. Donec quis mollis nisl. Vivamus et congue sapien. Ut augue nunc, varius vitae tellus vitae, pretium egestas leo. Cras luctus sem quis augue ornare, non sodales ipsum blandit.', 'company.png', 'companyEnv.png'),
(24, 'Common Sense Media', 'Vestibulum id nibh at magna pharetra accumsan.', 'Nunc odio nisi, sodales sed purus in, mattis facilisis sem. Fusce lorem est, convallis at rhoncus sed, congue a diam. Aenean vehicula tempus sapien, eu iaculis nulla vulputate vitae. Donec pharetra ex vitae aliquam tempor. Integer in tortor dolor. Proin in nisi felis. Nullam ac ante et leo maximus vulputate a ut nibh. Pellentesque eget arcu quis sem tempor scelerisque ac in turpis. Sed eget augue at nibh tincidunt varius sit amet nec nisl. Nunc eget dapibus lorem. Fusce dapibus gravida orci, at vulputate metus vehicula et. Suspendisse malesuada nulla in ante vestibulum, quis placerat nunc egestas. Donec sed posuere arcu. Proin porta sit amet sem ac varius.', 'company.png', 'companyEnv.png'),
(25, 'Sonos', 'Pellentesque quis orci et nisi ornare tempor quis et sem.', 'Vivamus ac urna risus. Proin eu sem urna. Maecenas bibendum lacus non massa pulvinar cursus. Donec turpis urna, imperdiet a lectus et, dictum suscipit ex. Vivamus gravida vestibulum sapien sed mollis. Suspendisse eu libero nulla. Aenean vestibulum dui ac quam feugiat, in finibus orci pellentesque. Etiam massa magna, tempor bibendum enim id, blandit suscipit nulla. Vestibulum vel neque massa. Donec sed tortor arcu. Vivamus sodales metus quis sodales convallis. Nullam sollicitudin leo dui, quis ultrices justo consectetur ornare.', 'company.png', 'companyEnv.png'),
(26, 'The Home Depot', 'Donec nec sem accumsan, varius tellus non, scelerisque erat.', 'Sed non suscipit augue, in blandit lorem. Morbi consectetur in arcu ac cursus. Sed commodo tellus non auctor venenatis. Donec neque mauris, vestibulum eget ipsum eu, ultrices interdum nunc. Quisque tellus quam, iaculis vitae facilisis dignissim, sollicitudin sed nisl. Integer dui est, varius sed lorem vitae, hendrerit posuere dolor. Suspendisse potenti. Aenean nec velit et mi cursus iaculis.', 'company.png', 'companyEnv.png'),
(27, 'Sovos', 'Aliquam placerat justo at neque aliquet, nec dignissim mauris eleifend.', 'Nulla ipsum turpis, dignissim in iaculis ut, auctor et elit. Aenean ullamcorper mattis mauris, non ultrices lorem gravida ac. Phasellus placerat tristique justo, vel pretium sem tincidunt vitae. Integer posuere ligula ut nulla tincidunt ultricies. Morbi vel mattis sem. Duis vel dapibus ligula. Duis feugiat elit sapien, in bibendum sapien accumsan id. Sed venenatis lobortis sem et condimentum.', 'company.png', 'companyEnv.png'),
(28, 'Community First Foundation', 'Pellentesque in felis congue, imperdiet felis ut, rhoncus nulla.', 'Ut aliquam ullamcorper mi sed pretium. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eget facilisis libero, non porttitor ex. Proin nibh libero, tincidunt venenatis metus at, eleifend auctor erat. Nam velit nisi, hendrerit vitae erat vitae, mollis vehicula erat. Fusce auctor nisl at justo sagittis, sit amet suscipit purus vestibulum. In congue tempor justo, sed convallis purus posuere a. Proin posuere nunc tincidunt augue pulvinar viverra vel eget enim. Suspendisse porta fermentum nibh nec dignissim.', 'company.png', 'companyEnv.png'),
(29, 'New Relic', 'In non libero vulputate augue viverra tincidunt.', 'Aliquam erat volutpat. Donec hendrerit quam at lectus faucibus, quis porta erat congue. In vitae aliquam leo. Integer scelerisque euismod magna a blandit. Vivamus mattis, ante eget eleifend maximus, justo purus aliquet erat, vel ullamcorper arcu nunc ac arcu. Maecenas porttitor lobortis mauris in fringilla. Morbi tempus eros non odio laoreet, sit amet ullamcorper felis aliquet.', 'company.png', 'companyEnv.png'),
(30, 'Wiley Edge', 'Etiam in tellus vitae libero consectetur fermentum.', 'Pellentesque sed quam cursus, posuere nunc a, imperdiet ante. Nam id interdum sem. Pellentesque tempus, quam et varius tincidunt, ipsum orci ornare eros, eget ornare sapien diam eu odio. Cras viverra, sem quis varius fermentum, metus felis lobortis erat, molestie luctus eros justo eget odio. Integer pharetra varius purus, vitae dignissim urna iaculis nec. Proin quis sodales dolor. Proin eleifend, diam et iaculis suscipit, elit neque dignissim magna, vitae mollis ex sem vel felis. Maecenas fringilla tempor imperdiet. Integer convallis dui ut nibh tempor interdum. Ut ornare eleifend rutrum. Suspendisse aliquet tempor dictum. Curabitur eget posuere sapien. Quisque eleifend est ullamcorper fermentum rutrum. Aliquam convallis mi nec lacus congue blandit. Duis ac leo sit amet dolor molestie viverra eu ac lectus.', 'company.png', 'companyEnv.png'),
(31, 'Black Rock', 'Nulla at diam quis ipsum consectetur mollis vel posuere ipsum.', 'Integer nunc purus, blandit sit amet sodales sit amet, porttitor ornare felis. Proin eleifend accumsan libero eu ultrices. Phasellus fringilla malesuada quam in hendrerit. Sed dignissim lacus quis elementum congue. Vestibulum ut faucibus lorem. Vestibulum vel nisl sed nulla luctus interdum. Nullam vitae mollis urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Mauris felis est, pellentesque vitae lacus sit amet, blandit sollicitudin ipsum. Curabitur commodo, dolor et accumsan feugiat, nisl ex vestibulum odio, in molestie libero metus ac nisi. Nulla facilisi.', 'company.png', 'companyEnv.png'),
(32, 'iZotope', 'Quisque eleifend elit sit amet tincidunt porta.', 'Aenean quis purus in tellus fermentum aliquet ac eu ipsum. Integer rutrum commodo ipsum, eget porta leo mattis ac. Nunc ornare est mi, vel lobortis lorem feugiat sed. Praesent ornare massa quis ornare vestibulum. Quisque urna mauris, fermentum eu rutrum sed, ornare vel dolor. Pellentesque odio nulla, iaculis bibendum quam porta, lobortis tempus felis. Mauris eleifend ante aliquet consequat venenatis. Sed sodales, ipsum ut pharetra vestibulum, augue libero scelerisque neque, vestibulum ultrices urna est ac est. Quisque et augue molestie, mollis metus sit amet, varius sem. Aliquam malesuada est at ullamcorper dictum. Nam scelerisque sapien ut felis malesuada fringilla. Curabitur vel iaculis leo.', 'company.png', 'companyEnv.png');

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `vacancy`
--

DROP TABLE IF EXISTS `vacancy`;
CREATE TABLE IF NOT EXISTS `vacancy` (
  `ID` int(5) NOT NULL AUTO_INCREMENT COMMENT 'unique ID for position',
  `title` text NOT NULL,
  `date` date NOT NULL,
  `type` text NOT NULL,
  `company_ID` int(11) NOT NULL COMMENT 'company''s ID',
  `contingency` text NOT NULL,
  `location` text NOT NULL,
  `URL` text NOT NULL,
  `perks` text NOT NULL,
  `seniority` text NOT NULL,
  `area` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM AUTO_INCREMENT=101 DEFAULT CHARSET=utf8;

--
-- Volcado de datos para la tabla `vacancy`
--

INSERT INTO `vacancy` (`ID`, `title`, `date`, `type`, `company_ID`, `contingency`, `location`, `URL`, `perks`, `seniority`, `area`) VALUES
(1, 'Senior Android Developer', '2022-03-10', 'Temporary', 1, 'Yes', 'Mexico ; Mexico-Remote ;', 'https://www.bounteous.com', '', 'Senior Level', 'IT & Cybersecurity'),
(2, 'Security Architect', '2022-03-10', 'Full Time', 2, 'No', 'MA-Other ;', 'https://www.americantower.com/', '', 'Senior Level', 'IT & Cybersecurity'),
(3, 'Software Engineer (L5) - AVTnT (Audio Video Test & Tools)', '2022-03-10', 'Full Time', 3, 'No', 'CA-Other ;', 'https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin', '', 'Mid Level', 'Engineering'),
(4, 'Sr Mobile UX/UI Designer', '2022-03-10', 'Internship', 4, 'No', 'AZ-Phoenix ; CA-San Francisco ; FL-Orlando ; IL-Chicago ; IN-Indianapolis ; MI-Other ; MO-St. Louis ; NJ-Jersey City ; TX-Austin ; TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Design'),
(5, 'Project Manager', '2022-03-10', 'Full Time', 4, 'No', 'CO-Denver ; TX-Austin ; TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Project Management'),
(6, 'Software Engineering Manager', '2022-03-10', 'Full Time', 5, 'No', 'TX-Austin ; TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Engineering'),
(7, 'Product Owner', '2022-03-10', 'Full Time', 4, 'No', 'Remote ; AZ-Phoenix ; CA-San Francisco ; CO-Denver ; IL-Chicago ; TX-Austin ; TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Other'),
(8, 'LAC Software Engineering Manager', '2022-03-10', 'Full Time', 6, 'No', 'Mexico ;', 'http://qualtrics.com', 'remotefriendly ; paidparentalleave ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Engineering'),
(9, 'Database Administrator', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'http://wikimediafoundation.org', '', 'Mid Level', 'Engineering'),
(10, 'Senior Manager, Site Reliability Engineering', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Management', 'Engineering'),
(11, 'Senior Product Manager, Platform', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Product'),
(12, 'Staff Site Reliability Engineer (Traffic)', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Senior Level', 'Engineering'),
(13, 'Senior Software Engineer - Structured Data', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Engineering'),
(14, 'Platform Engineering Manager', '2022-03-10', 'Full Time', 8, 'No', 'Remote ;', 'https://www.honeycomb.io/', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;', 'Management', 'Engineering'),
(15, 'Principal Software Engineer', '2022-03-10', 'Full Time', 9, 'No', 'OR-Portland ;', 'http://jobs.nike.com', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(16, 'Principal Data Engineer', '2022-03-10', 'Temporary', 9, 'Yes', 'Remote ;', 'http://jobs.nike.com', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(17, 'Director of Engineering - AI/ML Technology Foundation', '2022-03-10', 'Freelance', 9, 'Yes', 'Remote ;', 'http://jobs.nike.com', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Engineering'),
(18, 'Lead Analyst', '2022-03-10', 'Full Time', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Mid Level', 'Project Management'),
(19, 'Sr. Solution Architect', '2022-03-10', 'Full Time', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Senior Level', 'IT & Cybersecurity'),
(20, 'Sr .Net Developer w/ AWS experience', '2022-03-10', 'Full Time', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Senior Level', 'IT & Cybersecurity'),
(21, 'Senior Policy Admin & Billing Developer', '2022-03-10', 'Internship', 11, 'No', 'CA-Other ;', 'http://statefundca.com', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'IT & Cybersecurity'),
(22, 'Data Integration Specialist', '2022-03-10', 'Full Time', 12, 'No', 'Remote ; Hybrid ;', 'https://blackknight.wd1.myworkdayjobs.com/BKC/0/refreshFacet/318c8bb6f553100021d223d9780d30be', '', 'Mid Level', 'Data & Analytics'),
(23, 'Director of Marketing Operations', '2022-03-10', 'Internship', 13, 'No', 'Remote ;', 'https://lattice.com/', '', 'Management', 'Marketing'),
(24, 'Vice President, Product and Segment Marketing', '2022-03-10', 'Full Time', 13, 'No', 'Remote ; CA-San Francisco ;', 'https://lattice.com/', '', 'Management', 'Marketing'),
(25, 'Product Manager', '2022-03-10', 'Freelance', 14, 'Yes', 'Remote ;', 'https://www.firemon.com', '', 'Mid Level', 'Product'),
(26, 'Software Development Engineer', '2022-03-10', 'Full Time', 15, 'No', 'TN-Nashville ; TX-Austin ; WA-Seattle ;', 'https://www.amazon.jobs/en/jobs/2229899/software-development-engineer', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Engineering'),
(27, 'Software Engineer III - Web Team', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Product'),
(28, 'Technical Project Manager - Google Analytics/Digital Analytics', '2022-03-10', 'Full Time', 16, 'No', 'Remote ; US ;', 'https://infotrust.com/', '', 'Mid Level', 'Other'),
(29, 'Lead Counsel', '2022-03-10', 'Temporary', 7, 'Yes', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Senior Level', 'Legal'),
(30, 'Director of Product Management, Growth and Adoption', '2022-03-10', 'Full Time', 17, 'No', 'CA-San Francisco ;', 'https://boards.greenhouse.io/asana?gh_src=77d2661c1us', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Product'),
(31, 'Director of Product Management, Orchestrate', '2022-03-10', 'Full Time', 17, 'No', 'CA-San Francisco ;', 'https://boards.greenhouse.io/asana?gh_src=77d2661c1us', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Product'),
(32, 'Marketing Operations Manager', '2022-03-10', 'Internship', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Marketing'),
(33, 'Website Marketing Manager', '2022-03-10', 'Internship', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Junior Level', 'Marketing'),
(34, 'Product Marketing Manager', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Marketing'),
(35, 'Data Visualization Specialist (Contract)', '2022-03-10', 'Full Time', 7, 'No', 'Remote ; US ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Data & Analytics'),
(36, 'Systems Software Engineer (E4) - Device Platform Infrastructure', '2022-03-10', 'Full Time', 3, 'No', 'CA-Other ;', 'https://jobs.netflix.com/?utm_campaign=LIHomePage&utm_source=linkedin', '', 'Mid Level', 'Engineering'),
(37, 'Remote Senior .NET Developer', '2022-03-10', 'Full Time', 4, 'No', 'Remote ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(38, 'Senior DLP Engineer', '2022-03-10', 'Freelance', 4, 'Yes', 'Remote ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(39, 'Senior Product Manager', '2022-03-10', 'Full Time', 19, 'No', 'Remote ;', 'https://orum.io/', '', 'Mid Level', 'Product'),
(40, 'Member of Technical Staff 2', '2022-03-10', 'Full Time', 20, 'No', 'Remote ;', 'http://www.vmware.com', '', 'Junior Level', 'Engineering'),
(41, 'Principal, Responsible Technology', '2022-03-10', 'Full Time', 21, 'No', 'Hybrid ; CA-San Francisco ; CA-Other ; DC-Washington ; DC-Other ; MD-Baltimore ; MD-Other ; NY-New York City ; NY-Other ; VA-Arlington ; VA-Other ;', 'https://omidyar.com/', '', 'Mid Level', 'Business Strategy'),
(42, 'Engineering Lead Manager', '2022-03-10', 'Full Time', 22, 'No', 'TN-Nashville ;', 'https://fiber.google.com/', '', 'Mid Level', 'Operations'),
(43, 'Senior Product Engineer', '2022-03-10', 'Full Time', 8, 'No', 'Remote ;', 'https://www.honeycomb.io/', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ;', 'Senior Level', 'Engineering'),
(44, 'Manager, Partnership Success', '2022-03-10', 'Freelance', 23, 'Yes', 'CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Business Dev / Partnerships'),
(45, 'Sr. Data Scientist (Relay)', '2022-03-10', 'Freelance', 23, 'Yes', 'Remote ; CA-San Francisco ; NY-New York City ; UT-Other ; WA-Seattle ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Data & Analytics'),
(46, 'Senior Software Engineer', '2022-03-10', 'Full Time', 23, 'No', 'UT-Other ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(47, 'Staff Software Engineer, iOS', '2022-03-10', 'Full Time', 23, 'No', 'Remote ; CA-San Francisco ; UT-Other ; WA-Seattle ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(48, 'Strategic Finance Manager Operations', '2022-03-10', 'Freelance', 23, 'Yes', 'CA-San Francisco ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Finance'),
(49, 'Strategic Finance Senior Associate', '2022-03-10', 'Full Time', 23, 'No', 'Remote ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Finance'),
(50, 'Associate, Capital Management', '2022-03-10', 'Freelance', 23, 'Yes', 'Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Finance'),
(51, 'People Operations Associate', '2022-03-10', 'Freelance', 23, 'Yes', 'UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Junior Level', 'Human Resources'),
(52, 'Privacy Manager', '2022-03-10', 'Full Time', 23, 'No', 'Remote ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Legal'),
(53, 'Collections Associate - Credit Card', '2022-03-10', 'Internship', 23, 'No', 'FL-Other ; UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Junior Level', 'Operations'),
(54, 'Facilities and Real Estate Manager', '2022-03-10', 'Full Time', 23, 'No', 'CA-San Francisco ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Operations'),
(55, 'Manager, Fraud Investigations', '2022-03-10', 'Full Time', 23, 'No', 'CA-Other ; FL-Other ; TX-Dallas ; UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Operations'),
(56, 'Member Service Representative- SoFi Money', '2022-03-10', 'Internship', 23, 'No', 'FL-Other ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Junior Level', 'Operations'),
(57, 'Senior Business Operations Analyst', '2022-03-10', 'Full Time', 23, 'No', 'FL-Other ; UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Junior Level', 'Operations'),
(58, 'Principal Product Manager, SoFi Bank', '2022-03-10', 'Freelance', 23, 'Yes', 'CA-San Francisco ; UT-Salt Lake City ; WA-Seattle ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Product'),
(59, 'Senior Product Manager, Invest', '2022-03-10', 'Freelance', 23, 'Yes', 'Remote ; CA-San Francisco ; NY-New York City ; UT-Salt Lake City ; WA-Seattle ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'Product'),
(60, 'Credit Risk Manager, Risk Management â€“ Credit Card', '2022-03-10', 'Full Time', 23, 'No', 'FL-Other ; TX-Dallas ; UT-Salt Lake City ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Management', 'IT & Cybersecurity'),
(61, 'Senior Risk Data Analyst, Fraud Prevention', '2022-03-10', 'Full Time', 23, 'No', 'Remote ; CA-San Francisco ; NY-New York City ; TX-Dallas ;', 'http://www.sofi.com/careers', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Junior Level', 'IT & Cybersecurity'),
(62, 'Mobile App Product Manager', '2022-03-10', 'Full Time', 24, 'No', 'Remote ;', 'http://www.commonsensemedia.org', '', 'Mid Level', 'Engineering'),
(63, 'Senior Software Engineer (Java)', '2022-03-10', 'Full Time', 4, 'No', 'TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(64, '.NET Developer III', '2022-03-10', 'Full Time', 4, 'No', 'TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'IT & Cybersecurity'),
(65, 'Salesforce Developer', '2022-03-10', 'Temporary', 4, 'Yes', 'AZ-Phoenix ; NE-Omaha ; TX-Austin ; TX-Dallas ;', 'https://jobs.schwabjobs.com/', 'remotefriendly ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'IT & Cybersecurity'),
(66, 'Senior Sales Manager, Mexico', '2022-03-10', 'Internship', 25, 'No', 'Remote ;', 'https://www.sonos.com/en-us/life-at-sonos', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Mid Level', 'Sales'),
(67, 'Senior Director Product Management', '2022-03-10', 'Full Time', 26, 'No', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Senior Level', 'Product'),
(68, 'Senior QA Engineer', '2022-03-10', 'Freelance', 27, 'Yes', 'MA-Other ;', 'https://hrbrg.co/gpi756', '', 'Senior Level', 'IT & Cybersecurity'),
(69, 'Senior Project Manager (Communications)', '2022-03-10', 'Temporary', 7, 'Yes', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Senior Level', 'Project Management'),
(70, 'Software Engineer III - .NET', '2022-03-10', 'Freelance', 27, 'Yes', 'MN-Other ;', 'https://hrbrg.co/gpi756', '', 'Mid Level', 'IT & Cybersecurity'),
(71, 'Manager, UX', '2022-03-10', 'Full Time', 27, 'No', 'GA-Atlanta ;', 'https://hrbrg.co/gpi756', '', 'Management', 'IT & Cybersecurity'),
(72, 'Sr. Product Manager', '2022-03-10', 'Temporary', 26, 'Yes', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Mid Level', 'Product'),
(73, 'Product Manager', '2022-03-10', 'Temporary', 26, 'Yes', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Junior Level', 'Product'),
(74, 'Staff Systems Engineer', '2022-03-10', 'Internship', 26, 'No', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Mid Level', 'Engineering'),
(75, 'Sr. Systems Engineer', '2022-03-10', 'Full Time', 26, 'No', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(76, 'Sr. User Experience Designers', '2022-03-10', 'Freelance', 26, 'Yes', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Senior Level', 'Design'),
(77, 'Principal Software Engineer', '2022-03-10', 'Internship', 26, 'No', 'Remote ;', 'http://careers.homedepot.com/technology', 'remotefriendly ; paidparentalleave ; latinxintech ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(78, 'Nonprofit Success Manager', '2022-03-10', 'Full Time', 28, 'No', 'Hybrid ; CO-Denver ;', 'https://www.communityfirstfoundation.org/', '', 'Mid Level', 'Support'),
(79, 'Lead Data Engineer', '2022-03-10', 'Freelance', 29, 'Yes', 'Remote ;', 'https://newrelic.com/', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Other'),
(80, 'Senior Frontend Software Engineer - (Remote)', '2022-03-10', 'Full Time', 29, 'No', 'Remote ;', 'https://newrelic.com/', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(81, 'Senior Product Designer', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Product'),
(82, 'Senior Technical Writer', '2022-03-10', 'Temporary', 18, 'Yes', 'Remote ;', 'https://chronosphere.io/', '', 'Junior Level', 'Product'),
(83, 'Customer Solutions Engineer', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Other'),
(84, 'Senior Software Engineer - Frontend', '2022-03-10', 'Freelance', 18, 'Yes', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Engineering'),
(85, 'Head of Corporate Communications', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Management', 'Marketing'),
(86, 'Technical Content Writer', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Junior Level', 'Marketing'),
(87, 'Aspire Program â€“ Tech Careers for Women', '2022-03-10', 'Full Time', 30, 'No', 'NY-New York City ;', 'https://www.wileyedge.com', '', 'Junior Level', 'Engineering'),
(88, 'Sr Manager GTM G&A Talent Team', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'People Ops'),
(89, 'Workplace Experience Manager', '2022-03-10', 'Freelance', 18, 'Yes', 'NY-New York City ;', 'https://chronosphere.io/', '', 'Junior Level', 'People Ops'),
(90, 'Lead Software Engineer - Identity (Remote)', '2022-03-10', 'Full Time', 29, 'No', 'Remote ;', 'https://newrelic.com/', 'remotefriendly ; unlimitedvacation ; paidparentalleave ; latinxintech ; womenintecherg ; lgbtqierg-2 ;', 'Senior Level', 'Engineering'),
(91, 'DevOps Engineer', '2022-03-10', 'Internship', 32, 'No', 'MA-Boston ;', 'http://izotope.com', 'remotefriendly ; unlimitedvacation ; paidparentalleave ;', 'Mid Level', 'IT & Cybersecurity'),
(92, 'Sr Manager, App Dev', '2022-03-10', 'Internship', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Senior Level', 'IT & Cybersecurity'),
(93, 'Sr. Solution Architect', '2022-03-10', 'Full Time', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Senior Level', 'IT & Cybersecurity'),
(94, 'Lead DevOps Engineer', '2022-03-10', 'Full Time', 10, 'No', 'CA-San Francisco ;', 'https://www.frbsf.org/our-district/careers/', '', 'Mid Level', 'IT & Cybersecurity'),
(95, 'Senior Software Engineer', '2022-03-10', 'Internship', 17, 'No', 'IL-Chicago ;', 'https://www.mcmaster.com/careers', '', 'Mid Level', 'Engineering'),
(96, 'Data Center Engineer (contract, part-time)', '2022-03-10', 'Full Time', 7, 'No', 'TX-Other ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Engineering'),
(97, 'Integrated Marketing Specialist', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Mid Level', 'Marketing'),
(98, 'Legal Fellow (Spring 2023)', '2022-03-10', 'Full Time', 7, 'No', 'Remote ;', 'https://wikimediafoundation.org/', '', 'Junior Level', 'Legal'),
(99, 'Senior Software Engineer - Platform', '2022-03-10', 'Full Time', 18, 'No', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Engineering'),
(100, 'Senior Software Engineer - Infrastructure', '2022-03-10', 'Freelance', 18, 'Yes', 'Remote ;', 'https://chronosphere.io/', '', 'Mid Level', 'Engineering');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
